config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  delete '/logout' => 'sessions#destroy'

  resources :contractors
  resources :projects
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :projects
  has_many :users, through: :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :contractor
  accepts_nested_attributes_for :contractor
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :contractors, through: :projects

  validates :username, uniqueness: true, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

def new
  @project = Project.new
  @project.build_contractor
end

def create
  @project = Project.new(project_params)
  @project.user_id = session[:user_id]
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
end

private

def project_params
  params.require(:project).permit(:nickname, :description, :contractor_id,
  contractor_attributes: [:name])
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  def new
  end

  def create
    #find the user in database
    @user = User.find_by(username: params[:user][:username])
    #does the user exist and is their password correct?
    if @user.try(:authenticate, params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Incorrect Username or Password."
      redirect_to login_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlipTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <%= link_to 'Logout', logout_path, method: :delete %>
    <%= link_to 'Create Project', new_project_path %>

  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/new.html.erb
<h1> Create a New Project </h1>

<%= form_for(@project) do |f|%>

  <div>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.label :year_built %>
  <%= f.text_field :year_built %>

  <%= f.label :square_footage %>
  <%= f.text_field :square_footage %>

  <%= f.label :pool %>
  <%= f.text_field :pool %>

  <%= f.label :garage %>
  <%= f.text_field :garage %>

  <%= f.label :bedrooms %>
  <%= f.text_field :bedrooms %>

  <%= f.label :bathrooms %>
  <%= f.text_field :bathrooms %>

  <%= f.label :purchase_price %>
  <%= f.text_field :purchase_price %>

  <%= f.label :sale_price %>
  <%= f.text_field :sale_price %>

  <%= f.label :renovation_budget %>
  <%= f.text_field :renovation_budget %>

  <%= f.label :profit %>
  <%= f.text_field :profit %>

  <%= f.label :current_status %>
  <%= f.text_field :current_status %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <p><b> Select a Contractor </b></p>
    <div>
      <%= f.collection_select :contractor_id, Contractor.all, :id, :name %>
    </div>

  <p><b> Create a Contractor </b></p>
    <div>
      <%= f.fields_for :contractor do |b| %>
        <%= b.label :name %>
        <%= b.text_field :name %>
        <%= b.label :phone_number %>
        <%= b.text_field :phone_number %>
      <% end %>
    </div>

  <%= f.submit "Create Project" %>

<% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for(@user) do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>, You're signed in.